In [1]:
import mysql.connector as connector
from mysql.connector import Error

try:
    # Establish the connection
    connection = connector.connect(
        host="localhost",         # Replace with your actual host if different
        user="root",     # Replace with your actual username
        password="xxxxx", # Replace with your actual password
        database="tictac_db"          # Replace with your actual database name
    )
    
    if connection.is_connected():
        # Fetch and print some server information
        db_info = connection.get_server_info()
        print("Connected to MySQL Server version ", db_info)
        
        # Create a cursor object
        cursor = connection.cursor()
        
        # Execute a simple query to verify the connection
        cursor.execute("SELECT DATABASE();")
        record = cursor.fetchone()
        print("You're connected to database: ", record)
        
        # Optional: Show tables in the connected database
        cursor.execute("SHOW TABLES;")
        tables = cursor.fetchall()
        print("Tables in the database:", tables)
        
        # Execute the specific query
        query = """
        SELECT * FROM aact_studies WHERE nct_id IN
        (SELECT DISTINCT t.nct_id
            FROM tictac_genes_diseases_associations AS t
            JOIN aact_studies AS s ON t.nct_id = s.nct_id
            WHERE t.tcrdTargetName LIKE '%Calcitonin receptor%'
            AND t.disease_name = 'Breast cancer');
        """
        cursor.execute(query)
        results = cursor.fetchall()
        
        # Print the results
        for row in results:
            print(row)

except Error as e:
    print("Error while connecting to MySQL", e)

finally:
    if connection.is_connected():
        cursor.close()
        connection.close()
        print("MySQL connection is closed")

Connected to MySQL Server version  8.0.37-cluster
You're connected to database:  ('tictac_db',)
Tables in the database: [('aact_conditions',), ('aact_conditions_mesh',), ('aact_drugs_chembl_activity',), ('aact_drugs_chembl_document_pubmed_records',), ('aact_drugs_chembl_target_component',), ('aact_references',), ('aact_studies',), ('sddt_links',), ('tictac_genes_diseases_associations',)]
('NCT00003893', 'Interventional', 'National Cancer Institute (NCI)', 'Phase 3', 'Completed', None, datetime.date(1998, 7, 31), '2250', 'Sequencing of Chemotherapy and Radiotherapy in Adjuvant Breast Cancer')
('NCT01434134', 'Interventional', 'University Hospital, Akershus', 'Phase 2', 'Completed', None, datetime.date(2011, 9, 30), '130', 'Prevention of Cardiac Dysfunction During Adjuvant Breast Cancer Therapy: A Randomized, Placebo-controlled, 2x2 Factorial, Double Blind Trial of Candesartan and Metoprolol')
('NCT01500577', 'Interventional', 'European Institute of Oncology', 'Phase 2', 'Completed', None, datetime.date(2005, 4, 30), '150', 'A Randomized Phase II Prevention Trial in Subjects at High Risk for Hormone Non-responsive Breast Cancer')
('NCT00006260', 'Interventional', 'Case Comprehensive Cancer Center', 'Phase 2', 'Completed', None, datetime.date(1997, 5, 31), '36', 'A Phase II Study Of An OutPatient Three Day VIP Regimen With Oral Mesna For Metastatic Breast Cancer')
('NCT00459771', 'Interventional', 'The Netherlands Cancer Institute', 'Phase 3', 'Completed', None, datetime.date(2007, 6, 30), '210', 'Prospective, Randomized, Pharmacological Intervention Study; Evaluating Effect of the Angiotensin II-receptor (AT1) Blocker Candesartan vs Placebo in Prevention of Trastuzumab-associated Cardiotoxicity in Patients Treated With Trastuzumab')
('NCT03454529', 'Interventional', 'Barbara Ann Karmanos Cancer Institute', 'Phase 2', 'Active, not recruiting', None, datetime.date(2018, 3, 9), '24', 'The Effect of Statins on Markers of Breast Cancer Proliferation and Apoptosis in Women With Early Stage Breast Cancer')
('NCT00123669', 'Interventional', 'Tata Memorial Hospital', 'Phase 2/Phase 3', 'Completed', None, datetime.date(1997, 10, 31), '1000', 'The Primary Progesterone Therapy for Operable Breast Cancer : A Randomized Controlled Trial')
('NCT00807950', 'Interventional', 'National University Hospital, Singapore', 'Phase 2', 'Unknown status', None, datetime.date(2008, 3, 31), '100', 'Phase II Study of Simvastatin in Primary Breast Cancer; Test of Its Potential Selectivity on Basal Subtype Breast Cancer')
('NCT00334542', 'Interventional', 'Sidney Kimmel Comprehensive Cancer Center at Johns Hopkins', 'Phase 2', 'Completed', None, datetime.date(2006, 3, 31), '50', 'A Phase II Study of Simvastatin in Women at High Risk for a New Breast Cancer')
('NCT03906669', 'Interventional', "St Vincent's Hospital", 'Phase 2', 'Recruiting', None, datetime.date(2018, 3, 20), '200', 'A Window of Opportunity Study of Endocrine Therapy With and Without Prometrium in Postmenopausal Women With Early Stage Hormone Receptor-positive Breast Cancer.')
('NCT03192293', 'Interventional', 'National University Hospital, Singapore', 'Phase 2', 'Unknown status', None, datetime.date(2017, 1, 20), '28', 'Single Arm Phase 2 Study of Metformin and Simvastatin in Addition to Fulvestrant in Metastatic Estrogen Receptor Positive Breast Cancer')
('NCT00455962', 'Interventional', 'Massachusetts General Hospital', 'Phase 1/Phase 2', 'Completed', None, datetime.date(2005, 1, 31), '23', 'Effect of Race on Gonadotropin Responses to Short Term Negative and Positive Feedback Effects of Gonadal Steroids')
MySQL connection is closed

In [2]:
import mysql.connector as connector
from mysql.connector import Error
import pandas as pd

try:
    # Establish the connection
    connection = connector.connect(
        host="localhost",         # Replace with your actual host if different
        user="root",     # Replace with your actual username
        password="xxxxx", # Replace with your actual password
        database="tictac_db"          # Replace with your actual database name
    )
    
    if connection.is_connected():
        # Fetch and print some server information
        db_info = connection.get_server_info()
        print("Connected to MySQL Server version ", db_info)
        
        # Create a cursor object
        cursor = connection.cursor()
        
        # Execute a simple query to verify the connection
        cursor.execute("SELECT DATABASE();")
        record = cursor.fetchone()
        print("You're connected to database: ", record)
        
        # Optional: Show tables in the connected database
        cursor.execute("SHOW TABLES;")
        tables = cursor.fetchall()
        print("Tables in the database:", tables)
        
        # Execute the specific query
        query = """
        SELECT * FROM aact_studies WHERE nct_id IN
        (SELECT DISTINCT t.nct_id
            FROM tictac_genes_diseases_associations AS t
            JOIN aact_studies AS s ON t.nct_id = s.nct_id
            WHERE t.tcrdTargetName LIKE '%Calcitonin receptor%'
            AND t.disease_name = 'Breast cancer');
        """
        cursor.execute(query)
        results = cursor.fetchall()
        
        # Get column names
        column_names = [i[0] for i in cursor.description]
        
        # Create a DataFrame
        df = pd.DataFrame(results, columns=column_names)
        
        # Display the DataFrame
        print(df)

except Error as e:
    print("Error while connecting to MySQL", e)

finally:
    if connection.is_connected():
        cursor.close()
        connection.close()
        print("MySQL connection is closed")

Connected to MySQL Server version  8.0.37-cluster
You're connected to database:  ('tictac_db',)
Tables in the database: [('aact_conditions',), ('aact_conditions_mesh',), ('aact_drugs_chembl_activity',), ('aact_drugs_chembl_document_pubmed_records',), ('aact_drugs_chembl_target_component',), ('aact_references',), ('aact_studies',), ('sddt_links',), ('tictac_genes_diseases_associations',)]
         nct_id      study_type  \
0   NCT00003893  Interventional
1   NCT01434134  Interventional
2   NCT01500577  Interventional
3   NCT00006260  Interventional
4   NCT00459771  Interventional
5   NCT03454529  Interventional
6   NCT00123669  Interventional
7   NCT00807950  Interventional
8   NCT00334542  Interventional
9   NCT03906669  Interventional
10  NCT03192293  Interventional
11  NCT00455962  Interventional

                                               source            phase  \
0                     National Cancer Institute (NCI)          Phase 3
1                       University Hospital, Akershus          Phase 2
2                      European Institute of Oncology          Phase 2
3                    Case Comprehensive Cancer Center          Phase 2
4                    The Netherlands Cancer Institute          Phase 3
5               Barbara Ann Karmanos Cancer Institute          Phase 2
6                              Tata Memorial Hospital  Phase 2/Phase 3
7             National University Hospital, Singapore          Phase 2
8   Sidney Kimmel Comprehensive Cancer Center at J...          Phase 2
9                               St Vincent's Hospital          Phase 2
10            National University Hospital, Singapore          Phase 2
11                     Massachusetts General Hospital  Phase 1/Phase 2

            overall_status start_date completion_date enrollment  \
0                Completed       None      1998-07-31       2250
1                Completed       None      2011-09-30        130
2                Completed       None      2005-04-30        150
3                Completed       None      1997-05-31         36
4                Completed       None      2007-06-30        210
5   Active, not recruiting       None      2018-03-09         24
6                Completed       None      1997-10-31       1000
7           Unknown status       None      2008-03-31        100
8                Completed       None      2006-03-31         50
9               Recruiting       None      2018-03-20        200
10          Unknown status       None      2017-01-20         28
11               Completed       None      2005-01-31         23

                                       official_title
0   Sequencing of Chemotherapy and Radiotherapy in...
1   Prevention of Cardiac Dysfunction During Adjuv...
2   A Randomized Phase II Prevention Trial in Subj...
3   A Phase II Study Of An OutPatient Three Day VI...
4   Prospective, Randomized, Pharmacological Inter...
5   The Effect of Statins on Markers of Breast Can...
6   The Primary Progesterone Therapy for Operable ...
7   Phase II Study of Simvastatin in Primary Breas...
8   A Phase II Study of Simvastatin in Women at Hi...
9   A Window of Opportunity Study of Endocrine The...
10  Single Arm Phase 2 Study of Metformin and Simv...
11  Effect of Race on Gonadotropin Responses to Sh...
MySQL connection is closed

In [3]:
import mysql.connector as connector
from mysql.connector import Error
import pandas as pd

def execute_query(connection, query):
    try:
        cursor = connection.cursor()
        cursor.execute(query)
        results = cursor.fetchall()
        column_names = [i[0] for i in cursor.description]
        df = pd.DataFrame(results, columns=column_names)
        return df
    except Error as e:
        print(f"Error: {e}")
        return None

def main():
    try:
        # Establish the connection
        connection = connector.connect(
            host="localhost",         # Replace with your actual host if different
            user="root",     # Replace with your actual username
            password="Je@#1978", # Replace with your actual password
            database="tictac_db"          # Replace with your actual database name
        )

        if connection.is_connected():
            # Fetch and print some server information
            db_info = connection.get_server_info()
            print("Connected to MySQL Server version ", db_info)
            
            # Verify the connection
            cursor = connection.cursor()
            cursor.execute("SELECT DATABASE();")
            record = cursor.fetchone()
            print("You're connected to database: ", record)
            
            # Optional: Show tables in the connected database
            cursor.execute("SHOW TABLES;")
            tables = cursor.fetchall()
            print("Tables in the database:", tables)
            
            # Queries
            queries = {
                "Study details for Calcitonin receptor in Breast cancer": """
                SELECT * FROM aact_studies WHERE nct_id IN
                (SELECT DISTINCT t.nct_id
                    FROM tictac_genes_diseases_associations AS t
                    JOIN aact_studies AS s ON t.nct_id = s.nct_id
                    WHERE t.tcrdTargetName LIKE '%Calcitonin receptor%'
                    AND t.disease_name = 'Breast cancer');
                """,
                "Highest mean rank score association": """
                SELECT *
                FROM tictac_genes_diseases_associations
                ORDER BY mean_rank_score DESC
                LIMIT 1;
                """,
                "Least mean rank score association": """
                SELECT *
                FROM tictac_genes_diseases_associations
                ORDER BY mean_rank_score ASC
                LIMIT 1;
                """,
                "Least mean rank score association (non-null)": """
                SELECT *
                FROM tictac_genes_diseases_associations
                WHERE mean_rank_score IS NOT NULL
                ORDER BY mean_rank_score ASC
                LIMIT 1;
                """,
                "Top 25 highest mean rank score associations": """
                SELECT *
                FROM tictac_genes_diseases_associations
                WHERE mean_rank_score IS NOT NULL
                ORDER BY mean_rank_score DESC
                LIMIT 25;
                """,
                "Heart disease associations with highest mean rank score of 100": """
                SELECT *
                FROM tictac_genes_diseases_associations
                WHERE disease_name LIKE '%heart%'
                  AND mean_rank_score = 100
                ORDER BY mean_rank_score DESC
                LIMIT 10;
                """
            }

            # Execute and display results for each query
            for description, query in queries.items():
                print(f"\nExecuting query: {description}")
                df = execute_query(connection, query)
                if df is not None:
                    print(df)
                else:
                    print("No results returned or error in query execution")

    except Error as e:
        print("Error while connecting to MySQL", e)

    finally:
        if connection.is_connected():
            cursor.close()
            connection.close()
            print("MySQL connection is closed")

if __name__ == "__main__":
    main()

Connected to MySQL Server version  8.0.37-cluster
You're connected to database:  ('tictac_db',)
Tables in the database: [('aact_conditions',), ('aact_conditions_mesh',), ('aact_drugs_chembl_activity',), ('aact_drugs_chembl_document_pubmed_records',), ('aact_drugs_chembl_target_component',), ('aact_references',), ('aact_studies',), ('sddt_links',), ('tictac_genes_diseases_associations',)]

Executing query: Study details for Calcitonin receptor in Breast cancer
         nct_id      study_type  \
0   NCT00003893  Interventional
1   NCT01434134  Interventional
2   NCT01500577  Interventional
3   NCT00006260  Interventional
4   NCT00459771  Interventional
5   NCT03454529  Interventional
6   NCT00123669  Interventional
7   NCT00807950  Interventional
8   NCT00334542  Interventional
9   NCT03906669  Interventional
10  NCT03192293  Interventional
11  NCT00455962  Interventional

                                               source            phase  \
0                     National Cancer Institute (NCI)          Phase 3
1                       University Hospital, Akershus          Phase 2
2                      European Institute of Oncology          Phase 2
3                    Case Comprehensive Cancer Center          Phase 2
4                    The Netherlands Cancer Institute          Phase 3
5               Barbara Ann Karmanos Cancer Institute          Phase 2
6                              Tata Memorial Hospital  Phase 2/Phase 3
7             National University Hospital, Singapore          Phase 2
8   Sidney Kimmel Comprehensive Cancer Center at J...          Phase 2
9                               St Vincent's Hospital          Phase 2
10            National University Hospital, Singapore          Phase 2
11                     Massachusetts General Hospital  Phase 1/Phase 2

            overall_status start_date completion_date enrollment  \
0                Completed       None      1998-07-31       2250
1                Completed       None      2011-09-30        130
2                Completed       None      2005-04-30        150
3                Completed       None      1997-05-31         36
4                Completed       None      2007-06-30        210
5   Active, not recruiting       None      2018-03-09         24
6                Completed       None      1997-10-31       1000
7           Unknown status       None      2008-03-31        100
8                Completed       None      2006-03-31         50
9               Recruiting       None      2018-03-20        200
10          Unknown status       None      2017-01-20         28
11               Completed       None      2005-01-31         23

                                       official_title
0   Sequencing of Chemotherapy and Radiotherapy in...
1   Prevention of Cardiac Dysfunction During Adjuv...
2   A Randomized Phase II Prevention Trial in Subj...
3   A Phase II Study Of An OutPatient Three Day VI...
4   Prospective, Randomized, Pharmacological Inter...
5   The Effect of Statins on Markers of Breast Can...
6   The Primary Progesterone Therapy for Operable ...
7   Phase II Study of Simvastatin in Primary Breas...
8   A Phase II Study of Simvastatin in Women at Hi...
9   A Window of Opportunity Study of Endocrine The...
10  Single Arm Phase 2 Study of Metformin and Simv...
11  Effect of Race on Gonadotropin Responses to Sh...

Executing query: Highest mean rank score association
   disease_name       tcrdTargetName uniprot   CID       nct_id        doid  \
0  hypertension  Cytochrome P450 2D6  P10635  2541  NCT00005520  doid:10763

   disease_term    itv_id    drug_name target_chembl_id  ...  \
0  hypertension  31187858  candesartan        CHEMBL289  ...

      disease_target nStudy reference_type      pmid  nPub publication_type  \
0  doid:10763-CYP2D6    134     background  11230366   786             None

   t_sum  nDiseaseMention mean_rank mean_rank_score
0   None           2256.0     794.0           100.0

[1 rows x 23 columns]

Executing query: Least mean rank score association
          disease_name                                    tcrdTargetName  \
0  Parkinson's disease  HERV-H_2q24.3 provirus ancestral Env polyprotein

  uniprot   CID       nct_id        doid         disease_term    itv_id  \
0  Q05BR4  6047  NCT00006077  doid:14330  Parkinson's disease  31255887

  drug_name target_chembl_id  ... disease_target nStudy reference_type  \
0  levodopa    CHEMBL2073719  ...           None   None     background

      pmid  nPub publication_type  t_sum nDiseaseMention mean_rank  \
0  4272516  None             None   None            None      None

  mean_rank_score
0            None

[1 rows x 23 columns]

Executing query: Least mean rank score association (non-null)
  disease_name                  tcrdTargetName uniprot   CID       nct_id  \
0    leiomyoma  Lysine-specific demethylase 4E  B2RXH2  5994  NCT00455962

       doid disease_term    itv_id     drug_name target_chembl_id  ...  \
0  doid:127   leiomyomas  31030160  progesterone    CHEMBL1293226  ...

   disease_target nStudy reference_type      pmid  nPub publication_type  \
0  doid:127-KDM4E      1         result  22049179     1           result

   t_sum  nDiseaseMention mean_rank mean_rank_score
0   None              1.0      0.75        0.094458

[1 rows x 23 columns]

Executing query: Top 25 highest mean rank score associations
    disease_name       tcrdTargetName uniprot   CID       nct_id        doid  \
0   hypertension  Cytochrome P450 2D6  P10635  2541  NCT00005520  doid:10763
1   hypertension  Cytochrome P450 2D6  P10635  2541  NCT00005520  doid:10763
2   hypertension  Cytochrome P450 2D6  P10635  2541  NCT00005520  doid:10763
3   hypertension  Cytochrome P450 2D6  P10635  2541  NCT00005520  doid:10763
4   hypertension  Cytochrome P450 2D6  P10635  2541  NCT00005520  doid:10763
5   hypertension  Cytochrome P450 2D6  P10635  2541  NCT00005520  doid:10763
6   hypertension  Cytochrome P450 2D6  P10635  2541  NCT00005520  doid:10763
7   hypertension  Cytochrome P450 2D6  P10635  2541  NCT00005520  doid:10763
8   hypertension  Cytochrome P450 2D6  P10635  2541  NCT00005520  doid:10763
9   hypertension  Cytochrome P450 2D6  P10635  2541  NCT00005520  doid:10763
10  hypertension  Cytochrome P450 2D6  P10635  2541  NCT00005520  doid:10763
11  hypertension  Cytochrome P450 2D6  P10635  2541  NCT00005520  doid:10763
12  hypertension  Cytochrome P450 2D6  P10635  2541  NCT00005520  doid:10763
13  hypertension  Cytochrome P450 2D6  P10635  2541  NCT00005520  doid:10763
14  hypertension  Cytochrome P450 2D6  P10635  2541  NCT00005520  doid:10763
15  hypertension  Cytochrome P450 2D6  P10635  2541  NCT00005520  doid:10763
16  hypertension  Cytochrome P450 2D6  P10635  2541  NCT00005520  doid:10763
17  hypertension  Cytochrome P450 2D6  P10635  2541  NCT00005520  doid:10763
18  hypertension  Cytochrome P450 2D6  P10635  2541  NCT00005520  doid:10763
19  hypertension  Cytochrome P450 2D6  P10635  2541  NCT00005520  doid:10763
20  hypertension  Cytochrome P450 2D6  P10635  2541  NCT00005520  doid:10763
21  hypertension  Cytochrome P450 2D6  P10635  2541  NCT00005520  doid:10763
22  hypertension  Cytochrome P450 2D6  P10635  2541  NCT00005520  doid:10763
23  hypertension  Cytochrome P450 2D6  P10635  2541  NCT00005520  doid:10763
24  hypertension  Cytochrome P450 2D6  P10635  2541  NCT00005520  doid:10763

    disease_term    itv_id    drug_name target_chembl_id  ...  \
0   hypertension  31187858  candesartan        CHEMBL289  ...
1   hypertension  31187858  candesartan        CHEMBL289  ...
2   hypertension  31187858  candesartan        CHEMBL289  ...
3   hypertension  31187858  candesartan        CHEMBL289  ...
4   hypertension  31187858  candesartan        CHEMBL289  ...
5   hypertension  31187858  candesartan        CHEMBL289  ...
6   hypertension  31187858  candesartan        CHEMBL289  ...
7   hypertension  31187858  candesartan        CHEMBL289  ...
8   hypertension  31187858  candesartan        CHEMBL289  ...
9   hypertension  31187858  candesartan        CHEMBL289  ...
10  hypertension  31187858  candesartan        CHEMBL289  ...
11  hypertension  31187858  candesartan        CHEMBL289  ...
12  hypertension  31187858  candesartan        CHEMBL289  ...
13  hypertension  31187858  candesartan        CHEMBL289  ...
14  hypertension  31187858  candesartan        CHEMBL289  ...
15  hypertension  31187858  candesartan        CHEMBL289  ...
16  hypertension  31187858  candesartan        CHEMBL289  ...
17  hypertension  31187858  candesartan        CHEMBL289  ...
18  hypertension  31187858  candesartan        CHEMBL289  ...
19  hypertension  31187858  candesartan        CHEMBL289  ...
20  hypertension  31187858  candesartan        CHEMBL289  ...
21  hypertension  31187858  candesartan        CHEMBL289  ...
22  hypertension  31187858  candesartan        CHEMBL289  ...
23  hypertension  31187858  candesartan        CHEMBL289  ...
24  hypertension  31187858  candesartan        CHEMBL289  ...

       disease_target nStudy reference_type      pmid  nPub publication_type  \
0   doid:10763-CYP2D6    134     background  11204288   786             None
1   doid:10763-CYP2D6    134     background  11551376   786             None
2   doid:10763-CYP2D6    134     background  12527744   786             None
3   doid:10763-CYP2D6    134     background  15797660   786             None
4   doid:10763-CYP2D6    134     background  14735111   786             None
5   doid:10763-CYP2D6    134     background  11080130   786             None
6   doid:10763-CYP2D6    134     background  15797660   786             None
7   doid:10763-CYP2D6    134     background  11080130   786             None
8   doid:10763-CYP2D6    134     background  14735111   786             None
9   doid:10763-CYP2D6    134     background  15683583   786             None
10  doid:10763-CYP2D6    134     background  11560297   786             None
11  doid:10763-CYP2D6    134     background  11230366   786             None
12  doid:10763-CYP2D6    134     background  14553962   786             None
13  doid:10763-CYP2D6    134     background  11230366   786             None
14  doid:10763-CYP2D6    134     background  12406976   786             None
15  doid:10763-CYP2D6    134     background  12517286   786             None
16  doid:10763-CYP2D6    134     background  11551376   786             None
17  doid:10763-CYP2D6    134     background  11560297   786             None
18  doid:10763-CYP2D6    134     background  12517286   786             None
19  doid:10763-CYP2D6    134     background  15174896   786             None
20  doid:10763-CYP2D6    134     background  12406976   786             None
21  doid:10763-CYP2D6    134     background  12527744   786             None
22  doid:10763-CYP2D6    134     background  14553962   786             None
23  doid:10763-CYP2D6    134     background  11204288   786             None
24  doid:10763-CYP2D6    134     background  15174896   786             None

    t_sum  nDiseaseMention mean_rank mean_rank_score
0    None           2256.0     794.0           100.0
1    None           2256.0     794.0           100.0
2    None           2256.0     794.0           100.0
3    None           2256.0     794.0           100.0
4    None           2256.0     794.0           100.0
5    None           2256.0     794.0           100.0
6    None           2256.0     794.0           100.0
7    None           2256.0     794.0           100.0
8    None           2256.0     794.0           100.0
9    None           2256.0     794.0           100.0
10   None           2256.0     794.0           100.0
11   None           2256.0     794.0           100.0
12   None           2256.0     794.0           100.0
13   None           2256.0     794.0           100.0
14   None           2256.0     794.0           100.0
15   None           2256.0     794.0           100.0
16   None           2256.0     794.0           100.0
17   None           2256.0     794.0           100.0
18   None           2256.0     794.0           100.0
19   None           2256.0     794.0           100.0
20   None           2256.0     794.0           100.0
21   None           2256.0     794.0           100.0
22   None           2256.0     794.0           100.0
23   None           2256.0     794.0           100.0
24   None           2256.0     794.0           100.0

[25 rows x 23 columns]

Executing query: Heart disease associations with highest mean rank score of 100
Empty DataFrame
Columns: [disease_name, tcrdTargetName, uniprot, CID, nct_id, doid, disease_term, itv_id, drug_name, target_chembl_id, molecule_chembl_id, gene_symbol, idgTDL, disease_target, nStudy, reference_type, pmid, nPub, publication_type, t_sum, nDiseaseMention, mean_rank, mean_rank_score]
Index: []

[0 rows x 23 columns]
MySQL connection is closed

In [4]:
pwd

'/home/jeremiah/aact_files_db'